config/routes.rb
Rails.application.routes.draw do
  root 'opinions#index'

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :opinions, only: [:index, :create]
  resources :followings, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '*all', to: 'application#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  } unless Rails.env.development?
end

app/views/layouts/_header_nav.html.erb
<header class="header position-fixed d-flex align-items-center">
  <h2 class="hidden">Header</h2>
  <nav class="header-navbar py-3 w-100 d-flex align-items-center justify-content-between">
    <%= link_to image_tag('logo.png', alt:'logo', width: 100, class:'color-correction'),
    root_path, class: "d-inline px-4" %>
    <ul class="header-navbar-links d-flex pr-2 px-md-4 justify-content-between flex-wrap align-items-center my-2">
      <li class="m-2 m-md-0"><%= link_to root_path do %>
        <i class="fas fa-pen"></i>
      <% end %></li>
      <li class="m-2 m-md-0"><%= link_to root_path do %>
        <i class="fas fa-search"></i>
      <% end %></li>
      <li class="m-2 m-md-0"><%= link_to edit_user_path(current_user) do %>
        <i class="fas fa-cog"></i>
      <% end %></li>
      <li class="m-2 m-md-0"><%= link_to logout_path, method: 'DELETE' do %>
        <i class="fas fa-sign-out-alt"></i>
      <% end %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_homepage_r_side_profile_picture_link.html.erb
<%= link_to profile_picture_circle(user, 40, alt: "user-thumbnail-picture", class_name:"new-user-thumb-pic mr-2"), user_path(user) %>

app/views/layouts/_homepage_right_side_nav.html.erb
<div class="who-to-follow-module">
  <h3 class="who-to-follow-module-title d-flex px-4 align-items-center justify-content-start">WHO TO FOLLOW</h3>
  <hr class="m-0">
  <% if users %>
    <ul class="recently-joined-users pt-3 py-md-3 px-4 m-0">
      <% users.each do |user| %>
        <li class="new-user-card d-flex mb-3">
          <%= render 'layouts/homepage_r_side_profile_picture_link', user: user %>
          <div class="new-user-info d-flex flex-column justify-content-center">
            <h3 class="new-user-name"><%= link_to user.fullname, user_path(user) %></h3>
            <% if user.followers.any? %>
              <p class="new-user-followed-by">Followed by <%= link_to user.followers.first.fullname, user_path(user.followers.first) %></p>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_left_side_menu.html.erb
<nav class="left-side-menu m-md-0 position-fixed">
  <h2 class="hidden">Left Menu</h2>
  <div class="left-menu-top d-md-block d-flex justify-content-between">
    <div class="left-menu-profile d-flex align-items-center flex-lg-row flex-md-column justify-content-md-center p-4">
      <%= profile_picture_square(current_user, 50, alt:"profile picture of logged user", class_name:"left-menu-profile-pic") %>
      <h2 class="mt-md-2 mt-0 ml-4 m-md-0 ml-lg-4 text-center"><%= current_user.fullname.upcase! %></h2>
    </div>
    <div class="left-menu-stats d-flex">
      <div
        class="left-menu-user-stats-box left-menu-user-stats-box-l d-flex flex-column justify-content-center align-items-center flex-shrink-0 flex-grow-0 py-4">
        <p class="user-stats-total-left-menu"><%= current_user.followings.count %></p>
        <p>Following</p>
      </div>
      <div
        class="left-menu-user-stats-box left-menu-user-stats-box-r d-flex flex-column justify-content-center align-items-center flex-shrink-0 flex-grow-0 py-4">
        <p class="user-stats-total-left-menu"><%= current_user.followers.count %></p>
        <p>Followers</p>
      </div>
    </div>
  </div>
  <ul class="left-menu-links d-flex d-md-block justify-content-evenly">
    <%= tag.li class: "left-menu-link-home d-flex align-items-center py-4 #{active_link_home}" do %>
      <%= link_to '', opinions_path, class:'stretched-link' %>
      <i class="fas fa-home ml-md-4 mr-3"></i>
      <h2>HOME</h2>
    <% end %>
    <%= tag.li class: "left-menu-link-profile d-flex align-items-center py-4 #{active_link_current_user}" do %>
      <%= link_to '', user_path(current_user), class:'stretched-link' %>
      <i class="fas fa-user ml-md-4 mr-3"></i>
      <h2>PROFILE</h2>
    <% end %>
  </ul>
</nav>

app/views/layouts/_right_side_nav.html.erb
<aside class="right-side-nav border-md-left">
  <%= yield %>
</aside>

app/views/layouts/_userpage_r_side_main_profile_picture.html.erb
<%= profile_picture_circle(user, 80, alt: "profile info picture", class_name:"profile-info-picture mx-2") %>

app/views/layouts/_userpage_right_side_nav.html.erb
<div class="profile-detailed-info">
  <div class="profile-info-actions p-4 d-flex flex-column align-items-center">
    <div class="profile-info-picture-div d-flex p-4 align-items-center">
      <%= follow_button(user) %>
      <%= render 'layouts/userpage_r_side_main_profile_picture', user: user %>
      <%= userpage_opinions_link(user) %>
    </div>
    <h2 class="profile-info-fullname text-center mb-1"><%= user.fullname.upcase %></h2>
    <p class="profile-info-username-handle"><%= "@#{user.username}" %></p>
  </div>
  <div class="profile-info-stats d-flex border-top border-bottom">
    <div class="user-stats-box d-flex flex-column justify-content-center align-items-center flex-shrink-0 flex-grow-0">
      <p class="user-stats-total"><%= user.opinions.count %></p>
      <p>Recipes</p>
    </div>
    <div class="user-stats-box d-flex flex-column justify-content-center align-items-center flex-shrink-0 flex-grow-0 border-right border-left">
      <p class="user-stats-total"><%= user.followings.count %></p>
      <p>Following</p>
    </div>
    <div class="user-stats-box d-flex flex-column justify-content-center align-items-center flex-shrink-0 flex-grow-0">
      <p class="user-stats-total"><%= user.followers.count %></p>
      <p>Followers</p>
    </div>
  </div>
</div>

<div class="followed-by-module">
  <h3 class="followed-by-module-title d-flex px-4 align-items-center justify-content-start">FOLLOWED BY</h3>
  <hr class="my-0 mx-4">
  <% if users %>
    <ul class="recently-joined-users pt-3 py-md-3 px-4 m-0">
      <% users.each do |user| %>
        <li class="follower-card d-flex justify-content-between mb-3 align-items-center">
          <div class="profile-info-div d-flex position-relative">
            <%= link_to '', user_path(user), class:'stretched-link' %>
            <%= profile_picture_circle(user, 40, alt: "user-thumbnail-picture", class_name:"new-user-thumb-pic mr-2")%>
            <div class="follower-info d-flex flex-column justify-content-center">
              <h3 class="follower-fullname"><%= user.fullname %></h3>
              <p class="follower-username"><%= "@#{user.username}" %></p>
            </div>
          </div>
          <%= follow_button_small(user) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_vote_module.html.erb
<div class="vote-module mt-3 mb-2 d-flex justify-content-between">
  <div class="vote-button-div d-flex align-items-center"><%= vote_button(opinion, path) %></div>
  <%= pluralize(opinion.votes.count, "vote") if opinion.votes.any? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReceipeBuddies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width">
    <meta property="og:title" content="Recipe Buddies" />
    <meta property="og:image" content="https://res.cloudinary.com/starsheriff/image/upload/v1630121234/website_thumbnail_dmljxw.png" />
    <meta property="og:description" content="Desktop-first responsive app for cooking enthusiasts" />
    <meta property="og:url" content="https://gentle-cliffs-69056.herokuapp.com" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="page-container position-relative">
      <%= yield %>
    </div>

    <script src="https://kit.fontawesome.com/2bdc450678.js" crossorigin="anonymous"></script>
  </body>
</html>